[project]
name = "checker-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "html5validator>=0.4.2",
]

[dependency-groups]
dev = [
    "ty>=0.0.1a31",
]
