[project]
name = "checker-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "html5validator>=0.4.2",
    "pymarkdownlnt>=0.9.33",
    "requests>=2.32.5",
    "ty>=0.0.1a31",
]
